import { AccountInterface } from 'src/app/types/Account.Interface';
import Genders from 'src/app/untils/enums/Gender';

export const accounts: AccountInterface[] = [
  {
    id: 0,
    account: 'liemking2902',
    name: 'Dinh Hoang Liem',
    dob: '2000-09-02',
    gender: Genders.MALE,
    address: '11/65 Vo Truong Toan, Can Tho',
    email: 'liemking2902@gmail.com',
    isDeleted: false,
  },
  {
    id: 1,
    account: 'tuandh7x',
    name: 'Dinh Hoang Tuan',
    dob: '1999-06-07',
    gender: Genders.MALE,
    address: '256 Can Tho 900000',
    email: 'tuan99@gmail.com',
    isDeleted: false,
  },
  {
    id: 2,
    account: 'hoa9x',
    name: 'Nguyen Thi Hoa',
    dob: '1994-03-03',
    gender: Genders.FEMALE,
    address: 'Chau Thanh A, Hau Giang',
    email: 'hoa94@gmail.com',
    isDeleted: false,
  },
  {
    id: 3,
    account: 'hue94',
    name: 'Nguyen Thi Hue',
    dob: '1994-05-06',
    gender: Genders.FEMALE,
    address: '1700 Ba Ria - Vung Tau',
    email: 'hue94@gmail.com',
    isDeleted: false,
  },
  {
    id: 4,
    account: 'tai1x',
    name: 'Nguyen Van Tai',
    dob: '1993-01-02',
    gender: Genders.MALE,
    address: 'Cho lang me, Đong Nai',
    email: 'tai@gmail.com',
    isDeleted: false,
  },
  {
    id: 5,
    account: 'hong94',
    name: 'Nguyen Thi Hong',
    dob: '1992-07-08',
    gender: Genders.FEMALE,
    address: '3MJM+J9W, Binh Thuan',
    email: 'hong@gmail.com',
    isDeleted: false,
  },
  {
    id: 6,
    account: 'huong92',
    name: 'Nguyen Thi Huong',
    dob: '1992-01-03',
    gender: Genders.FEMALE,
    address: '2DJ9W, An Giang',
    email: 'huong@gmail.com',
    isDeleted: false,
  },
  {
    id: 7,
    account: 'lan94',
    name: 'Nguyen Thi Lan',
    dob: '1994-07-09',
    gender: Genders.FEMALE,
    address: '3P6D, Hoa Binh',
    email: 'Lan@gmail.com',
    isDeleted: false,
  },
  {
    id: 8,
    account: 'kieu91',
    name: 'Nguyen Thi Kieu',
    dob: '1991-02-04',
    gender: Genders.FEMALE,
    address: '7DGH, Kien Giang',
    email: 'kieu@gmail.com',
    isDeleted: false,
  },
  {
    id: 9,
    account: 'kiet90',
    name: 'Nguyen Van Kiet',
    dob: '1990-04-05',
    gender: Genders.MALE,
    address: '8UIK, Phu Quoc',
    email: 'kiet@gmail.com',
    isDeleted: false,
  },
  {
    id: 10,
    account: 'tung89',
    name: 'Nguyen Van Tung',
    dob: '1989-04-06',
    gender: Genders.MALE,
    address: '1Pk3D, Hon Son',
    email: 'tung@gmail.com',
    isDeleted: false,
  },
  {
    id: 11,
    account: 'hung88',
    name: 'Nguyen Manh Hung',
    dob: '1988-05-02',
    gender: Genders.MALE,
    address: '6G7H, Hai Phong',
    email: 'hung@gmail.com',
    isDeleted: false,
  },
  {
    id: 12,
    account: 'tham97',
    name: 'Nguyen Hong Tham',
    dob: '1997-09-06',
    gender: Genders.FEMALE,
    address: '9T8H, Nam Son',
    email: 'tham@gmail.com',
    isDeleted: false,
  },
];

export function getAccountDetailById(id: number): AccountInterface | undefined {
  return accounts.find((acc) => Number(acc.id) === Number(id));
}
